# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "董晶-中国科学院自动化研究所"
  [zh.params]
    description = "董晶的个人主页"
  [[zh.menu.main]]
    name = "个人简介"
    url = "index.html#about"
    weight = 10
  [[zh.menu.main]]
    name = "学术任职"
    url = "index.html#accomplishments"
    weight = 18
  [[zh.menu.main]]
    name = "学术论文"
    url = "index.html#publications"
    weight = 20
  [[zh.menu.main]]
    name = "科研项目"
    url = "index.html#projects"
    weight = 30
  [[zh.menu.main]]
    name = "课题组人员"
    url = "index.html#people"
    weight = 40
  [[zh.menu.main]]
    name = "毕业生信息"
    url = "index.html#students"
    weight = 50	
  [[zh.menu.main]]
    name = "招生信息"
    url = "index.html#teaching"
    weight = 60


